title: Nick's Stuff
author: Nick Markopoulos
email: hello@nicholas.pizza
description: A personal website for things.

github_username: nsmarkop
twitter_username: nsmarkop

show_excerpts: false

remote_theme: minima
minima:
  date_format: "%Y-%m-%d"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
